spring.application.name=estudantes

# Explicita a permissão de envio de arquivo
spring.servlet.multipart.enabled=true

# Define o tamanho maximo do requisição do arquivo
spring.servlet.multipart.max-request-size=40MB

# Define o tamanho maximo de envio do arquivo
spring.servlet.multipart.max-file-size=40MB 

# Define onde o arquivo será salvo dentro da aplicação. Idealmente e melhor salvar fora da aplicação
spring.web.resources.static-locations=file:src/main/resources/static/,classpath:/static/