spring.application.name=persistencia_jpa

# Caminho do banco de dados do Driver
spring.datasource.url=jdbc:mysql://localhost:3306/jpa_aula?createDatabaseIfNotExist=true 

#?createDatabaseIfNotExist=true # Cria o banco de dados se ele nao existir
# &userSSL=false
# &serverTimezone=UTC
# ...

# Login no banco de dados
spring.datasource.username=root
spring.datasource.password=bancodedados

# ddl-auto: permite criação e atualização das tabelas do banco;
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# spring.jpa.show-sql=true